    /* ********************************************************************** */
    /* Program . . . . . T_CMD                                                */
    /*   Calls . . . . . T_CMD                                                */
    /*                                                                        */
    /* Created on  . . .                                                      */
    /*         by  . . .                                                      */
    /*                                                                        */
    /* Description . . . Command Template                                     */
    /*                                                                        */
    /* To Compile:                                                            */
    /* *> CRTCMD CMD(&O/&ON) SRCFILE(&L/&F) SRCMBR(&N) PGM(LIB/PGM)       <*  */
    /* *> DLTSPLF FILE(&N) SPLNBR(*LAST)                                  <*  */
    /*                                                                        */
    /* CHANGE LOG:                                                            */
    /* Date       | Name            | Description                             */
    /* ---------------------------------------------------------------------- */
    /*            |                 |                                         */
    /*            |                 |                                         */
    /*            |                 |                                         */
    /* ************************************************************************/
             CMD        PROMPT(T_CMD) 